var pois = [
  {
    ID: 677,
    title: 'Blue Fin',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 1,
    link: {
      title: 'Learn More ',
      url: 'https://www.bluefinnyc.com/',
      target: '_blank',
    },
    ubication: {
      address: '1567 Broadway, New York, NY 10036, United States',
      lat: 40.7594131,
      lng: -73.9856617,
      zoom: 14,
      place_id: 'ChIJK5K7y1VYwokR30lrozf6_PY',
      name: '1567 Broadway',
      street_number: '1567',
      street_name: 'Broadway',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 661,
    title: 'Whole Foods Market',
    size: 'little',
    colorfont: 'dark',
    color: '#e2afa8',
    num: 2,
    link: {
      title: 'Learn More ',
      url: 'http://www.wholefoodsmarket.com',
      target: '_blank',
    },
    ubication: {
      address: '1095 6th Ave, New York, NY 10036, United States',
      lat: 40.7547268,
      lng: -73.9847948,
      zoom: 14,
      place_id: 'ChIJd3SOyKpZwokRQhxfTt8BptQ',
      name: '1095 6th Ave',
      street_number: '1095',
      street_name: '6th Avenue',
      street_name_short: '6th Ave',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'lifestyle',
    child_cats: [],
  },
  {
    ID: 660,
    title: 'Soulcycle',
    size: 'little',
    colorfont: 'dark',
    color: '#e2afa8',
    num: 3,
    link: {
      title: 'Learn More ',
      url: 'https://www.soul-cycle.com/',
      target: '_blank',
    },
    ubication: {
      address: '123 W 41st St, New York, NY 10036, United States',
      lat: 40.7545492,
      lng: -73.98549640000002,
      zoom: 14,
      place_id:
        'EiYxMjMgVyA0MXN0IFN0LCBOZXcgWW9yaywgTlkgMTAwMzYsIFVTQSJQEk4KNAoyCc17oyerWcKJEbRY28iJFuIHGh4LEO7B7qEBGhQKEgkHI_iTU1jCiRHtZhXelmjV9wwQeyoUChIJkw2w6lJYwokRpXY8aQyrFx4',
      name: '123 W 41st St',
      street_number: '123',
      street_name: 'West 41st Street',
      street_name_short: 'W 41st St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'lifestyle',
    child_cats: [],
  },
  {
    ID: 658,
    title: 'Equinox Bryant Park',
    size: 'big',
    colorfont: 'dark',
    color: '#e2afa8',
    num: 4,
    link: {
      title: 'Learn More ',
      url: 'https://www.equinox.com/clubs/new-york/midtown/bryantpark',
      target: '_blank',
    },
    ubication: {
      address: '124 W 42nd St, New York, NY 10036, USA',
      lat: 40.75501108791392,
      lng: -73.9851286772461,
      zoom: 14,
      place_id: 'ChIJHb4nzqpZwokR5JXtX4ugHYE',
      street_number: '124',
      street_name: 'West 42nd Street',
      street_name_short: 'W 42nd St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'lifestyle',
    child_cats: [],
  },
  {
    ID: 657,
    title: 'Castell Rooftop Lounge',
    size: 'little',
    colorfont: 'white',
    color: '#79a050',
    num: 5,
    link: {
      title: 'Learn More ',
      url: 'https://www.castellnyc.com/?utm_source=GMBlisting&utm_medium=organic',
      target: '_blank',
    },
    ubication: {
      address:
        'AC Hotel New York Times Square, 260 W 40th St, New York, NY 10018, United States',
      lat: 40.75546250000001,
      lng: -73.9900798,
      zoom: 14,
      place_id: 'ChIJuT3vtqxZwokRdJL8AuaLEKo',
      name: 'AC Hotel New York Times Square',
      street_number: '260',
      street_name: 'West 40th Street',
      street_name_short: 'W 40th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10018',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'bar',
    child_cats: [],
  },
  {
    ID: 656,
    title: 'Bar 54',
    size: 'little',
    colorfont: 'white',
    color: '#79a050',
    num: 6,
    link: {
      title: 'Learn More ',
      url: 'https://www.hyatt.com/en-US/hotel/new-york/hyatt-centric-times-square-new-york/nycts/dining',
      target: '_blank',
    },
    ubication: {
      address: '135 W 45th St, New York, NY 10036, United States',
      lat: 40.7575283,
      lng: -73.9840627,
      zoom: 14,
      place_id: 'ChIJ_4N-dlVYwokRnbfwy-N3tr4',
      name: '135 W 45th St',
      street_number: '135',
      street_name: 'West 45th Street',
      street_name_short: 'W 45th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'bar',
    child_cats: [],
  },
  {
    ID: 655,
    title: 'The Stinger',
    size: 'little',
    colorfont: 'white',
    color: '#79a050',
    num: 7,
    link: '',
    ubication: {
      address:
        'InterContinental New York Times Square, 300 W 44th St, New York, NY 10036, United States',
      lat: 40.7586603,
      lng: -73.98954429999999,
      zoom: 14,
      place_id: 'ChIJmR9pnVNYwokRqHaZ7QNK4fE',
      name: 'InterContinental New York Times Square',
      street_number: '300',
      street_name: 'West 44th Street',
      street_name_short: 'W 44th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'bar',
    child_cats: [],
  },
  {
    ID: 654,
    title: 'III Pillars',
    size: 'big',
    colorfont: 'white',
    color: '#79a050',
    num: 8,
    link: {
      title: 'Learn More ',
      url: 'https://www.suzukinyc.com/',
      target: '_blank',
    },
    ubication: {
      address: '114w W 47th St, New York, NY 10036, United States',
      lat: 40.7580934,
      lng: -73.98314549999999,
      zoom: 14,
      place_id: 'ChIJRxSwh1VYwokRUZQBMr2Zbz8',
      name: '114w W 47th St',
      street_number: '114w',
      street_name: 'West 47th Street',
      street_name_short: 'W 47th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'bar',
    child_cats: [],
  },
  {
    ID: 653,
    title: 'Living Room',
    size: 'little',
    colorfont: 'white',
    color: '#79a050',
    num: 9,
    link: {
      title: 'Learn More ',
      url: 'http://wlivingroomtimessquare',
      target: '_blank',
    },
    ubication: {
      address: '1567 Broadway, New York, NY 10036, United States',
      lat: 40.7594131,
      lng: -73.9856617,
      zoom: 14,
      place_id: 'ChIJK5K7y1VYwokR30lrozf6_PY',
      name: '1567 Broadway',
      street_number: '1567',
      street_name: 'Broadway',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'bar',
    child_cats: [],
  },
  {
    ID: 652,
    title: 'The View',
    size: 'little',
    colorfont: 'white',
    color: '#79a050',
    num: 10,
    link: {
      title: 'Learn More ',
      url: 'https://www.marriott.com/hotels/hotel-information/restaurant/nycmq-new-york-marriott-marquis/',
      target: '_blank',
    },
    ubication: {
      address: '1535 Broadway, New York, NY 10036, United States',
      lat: 40.7585862,
      lng: -73.98582019999999,
      zoom: 14,
      place_id: 'ChIJ6UYFrlVYwokRMb8DsvI4m4U',
      name: '1535 Broadway',
      street_number: '1535',
      street_name: 'Broadway',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'bar',
    child_cats: [],
  },
  {
    ID: 651,
    title: 'St. Cloud Rooftop Bar',
    size: 'little',
    colorfont: 'white',
    color: '#79a050',
    num: 11,
    link: {
      title: 'Learn More ',
      url: 'https://theknickerbocker.com/dine/st-cloud/?utm_source=local-listings&utm_medium=organic&utm_campaign=local-listings',
      target: '_blank',
    },
    ubication: {
      address:
        '6th Avenue, Theater District, New York, NY 10036, United States',
      lat: 40.7586496,
      lng: -73.9813439,
      zoom: 15,
      place_id:
        'Eho2dGggQXZlLCBOZXcgWW9yaywgTlksIFVTQSIuKiwKFAoSCYsJgAwgWsKJERFNxE6ad2ddEhQKEgmDMPu4VVjCiRFcKgR28a75oA',
      name: '6th Avenue',
      street_name: '6th Avenue',
      street_name_short: '6th Ave',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'bar',
    child_cats: [],
  },
  {
    ID: 650,
    title: 'The Skylark',
    size: 'little',
    colorfont: 'white',
    color: '#79a050',
    num: 12,
    link: {
      title: 'Learn More ',
      url: 'https://theskylarknyc.com/',
      target: '_blank',
    },
    ubication: {
      address: '200 W 39th St, New York, NY 10018, United States',
      lat: 40.75421130000001,
      lng: -73.9888636,
      zoom: 14,
      place_id: 'ChIJN-STYqtZwokRLvmO3au7uYA',
      name: '200 W 39th St',
      street_number: '200',
      street_name: 'West 39th Street',
      street_name_short: 'W 39th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10018',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'bar',
    child_cats: [],
  },
  {
    ID: 648,
    title: 'Boqueria',
    size: 'big',
    colorfont: 'white',
    color: '#79a050',
    num: 13,
    link: {
      title: 'Learn More ',
      url: 'https://boqueriarestaurant.com/',
      target: '_blank',
    },
    ubication: {
      address: '602 8th Ave, New York, NY 10018, USA',
      lat: 40.75602231660199,
      lng: -73.9900926,
      zoom: 14,
      place_id: 'ChIJVVUptaxZwokR6VwCzsZ7vWM',
      street_number: '602',
      street_name: '8th Avenue',
      street_name_short: '8th Ave',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10018',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'bar',
    child_cats: [],
  },
  {
    ID: 646,
    title: 'Haru Sushi',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 14,
    link: {
      title: 'Learn More ',
      url: 'https://harusushi.com/',
      target: '_blank',
    },
    ubication: {
      address: '240 W 44th St, New York, NY 10036, USA',
      lat: 40.757940373589996,
      lng: -73.98773248042602,
      zoom: 16,
      place_id: 'ChIJ29WI81RYwokRgyUvvi6SkcQ',
      street_number: '240',
      street_name: 'West 44th Street',
      street_name_short: 'W 44th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 645,
    title: 'The Ribbon',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 15,
    link: {
      title: 'Learn More ',
      url: 'https://www.theribbonnyc.com/',
      target: '_blank',
    },
    ubication: {
      address: '200 W 44th St, New York, NY 10036, USA',
      lat: 40.7576035777389,
      lng: -73.98662811772155,
      zoom: 17,
      place_id: 'ChIJR9So-lRYwokRX1xEjA0rChA',
      street_number: '200',
      street_name: 'West 44th Street',
      street_name_short: 'W 44th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 633,
    title: 'Saju Bistro',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 16,
    link: {
      title: 'Learn More ',
      url: 'http://www.sajubistronyc.com/',
      target: '_blank',
    },
    ubication: {
      address: '120 W 44th St, New York, NY 10036, United States',
      lat: 40.7564107,
      lng: -73.9843398,
      zoom: 14,
      place_id: 'ChIJ-49XQFVYwokRCxYufk4uVTc',
      name: '120 W 44th St',
      street_number: '120',
      street_name: 'West 44th Street',
      street_name_short: 'W 44th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 632,
    title: 'The Lambs Club',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 17,
    link: {
      title: 'Learn More ',
      url: 'http://www.thelambsclub.com/',
      target: '_blank',
    },
    ubication: {
      address: '132 W 44th St, New York, NY 10036, United States',
      lat: 40.7565062,
      lng: -73.9846347,
      zoom: 14,
      place_id: 'ChIJoV3BP1VYwokR4-MmYnVErFc',
      name: '132 W 44th St',
      street_number: '132',
      street_name: 'West 44th Street',
      street_name_short: 'W 44th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 630,
    title: 'Charlie Palmer at The Knick',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 18,
    link: {
      title: 'Learn More ',
      url: 'https://www.charliepalmer.com/',
      target: '_blank',
    },
    ubication: {
      address: 'Times Square, NY, Manhattan, New York 10036, United States',
      lat: 40.7579747,
      lng: -73.9855426,
      zoom: 14,
      place_id: 'ChIJmQJIxlVYwokRLgeuocVOGVU',
      name: 'Times Square',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 629,
    title: 'Wolfgang\u2019s Steakhouse',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 19,
    link: {
      title: 'Learn More ',
      url: 'https://www.wolfgangssteakhouse.net/',
      target: '_blank',
    },
    ubication: {
      address: '250 West 41st Street, New York, NY, USA',
      lat: 40.7558213,
      lng: -73.9894612,
      zoom: 14,
      place_id: 'ChIJ4wPTUlNYwokRm4n6miX8aGU',
      name: '250 W 41st St',
      street_number: '250',
      street_name: 'West 41st Street',
      street_name_short: 'W 41st St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10018',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 628,
    title: 'Oceana',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 20,
    link: {
      title: 'Learn More ',
      url: 'https://www.oceanarestaurant.com/',
      target: '_blank',
    },
    ubication: {
      address: '120 W 49th St, New York, NY 10020, United States',
      lat: 40.7597437,
      lng: -73.982321,
      zoom: 14,
      place_id: 'ChIJcQqOS_9YwokRepayb9QXk3Q',
      name: '120 W 49th St',
      street_number: '120',
      street_name: 'West 49th Street',
      street_name_short: 'W 49th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10019',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 627,
    title: 'Dos Caminos',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 21,
    link: {
      title: 'Learn More ',
      url: 'https://www.doscaminos.com/',
      target: '_blank',
    },
    ubication: {
      address: '1567 Broadway, New York, NY 10036, United States',
      lat: 40.7594131,
      lng: -73.9856617,
      zoom: 14,
      place_id: 'ChIJK5K7y1VYwokR30lrozf6_PY',
      name: '1567 Broadway',
      street_number: '1567',
      street_name: 'Broadway',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 626,
    title: 'Butter Midtown',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 22,
    link: {
      title: 'Learn More ',
      url: 'https://www.butterrestaurant.com/',
      target: '_blank',
    },
    ubication: {
      address: '70 W 45th St, New York, NY 10036, United States',
      lat: 40.7563378,
      lng: -73.98221699999999,
      zoom: 14,
      place_id: 'ChIJH7KQkv9YwokRwgFw8k8cuGA',
      name: '70 W 45th St',
      street_number: '70',
      street_name: 'West 45th Street',
      street_name_short: 'W 45th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 624,
    title: 'Del Frisco\u2019s Double Eagle Steakhouse',
    size: 'big',
    colorfont: 'white',
    color: '#2a5780',
    num: 23,
    link: {
      title: 'Learn More ',
      url: 'https://delfriscos.com/steakhouse/new-york/',
      target: '_blank',
    },
    ubication: {
      address: '1221 6th Ave, New York, NY 10020, United States',
      lat: 40.7594995,
      lng: -73.9822451,
      zoom: 14,
      place_id: 'ChIJjaDoMP9YwokRfED1DszC2z8',
      name: '1221 6th Ave',
      street_number: '1221',
      street_name: '6th Avenue',
      street_name_short: '6th Ave',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10020',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 623,
    title: 'Gabriel Kreuther',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 24,
    link: {
      title: 'Learn More ',
      url: 'https://www.gabrielkreuthernyc.com/',
      target: '_blank',
    },
    ubication: {
      address: '41 W 42nd St, New York, NY 10036, United States',
      lat: 40.7545381,
      lng: -73.98250260000002,
      zoom: 14,
      place_id: 'ChIJQWr4BgBZwokR_t3o34UWZqo',
      name: '41 W 42nd St',
      street_number: '41',
      street_name: 'West 42nd Street',
      street_name_short: 'W 42nd St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 622,
    title: 'Sushi by Bou Times Square',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 25,
    link: {
      title: 'Read More',
      url: 'https://www.sushibybou.com/',
      target: '_blank',
    },
    ubication: {
      address: '132 W 47th St, New York, NY 10036, United States',
      lat: 40.7584057,
      lng: -73.9833062,
      zoom: 14,
      place_id: 'ChIJ6TLDh1VYwokR-bNiMqLa83k',
      name: '132 W 47th St',
      street_number: '132',
      street_name: 'West 47th Street',
      street_name_short: 'W 47th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 621,
    title: 'Hunt & Fish Club',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 26,
    link: {
      title: 'Learn More ',
      url: 'http://places.singleplatform.com/hunt--fish-club-nyc/menu?ref=google#menu_1494358',
      target: '_blank',
    },
    ubication: {
      address: '125 W 44th St, New York, NY 10036, United States',
      lat: 40.7568129,
      lng: -73.98424299999999,
      zoom: 14,
      place_id: 'ChIJYZp-a1VYwokRsLvcC14NA-k',
      name: '125 W 44th St',
      street_number: '125',
      street_name: 'West 44th Street',
      street_name_short: 'W 44th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 620,
    title: 'Osteria Al Doge',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 27,
    link: {
      title: 'Learn More ',
      url: 'http://www.osteriaaldogenyc.com/',
      target: '_blank',
    },
    ubication: {
      address: '142 W 44th St, New York, NY 10036, United States',
      lat: 40.7566272,
      lng: -73.98491369999999,
      zoom: 14,
      place_id: 'ChIJWZgeFlVYwokR4FXCn8HFh90',
      name: '142 W 44th St',
      street_number: '142',
      street_name: 'West 44th Street',
      street_name_short: 'W 44th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 619,
    title: 'Ortzi',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 28,
    link: {
      title: 'Learn More ',
      url: 'https://ortzirestaurant.com/',
      target: '_blank',
    },
    ubication: {
      address: '120 W 41st St, New York, NY 10036, United States',
      lat: 40.7543813,
      lng: -73.9858102,
      zoom: 14,
      place_id: 'ChIJV4mp36pZwokRtB2Qzmq9j88',
      name: '120 W 41st St',
      street_number: '120',
      street_name: 'West 41st Street',
      street_name_short: 'W 41st St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 618,
    title: 'Burger & Lobster',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 29,
    link: {
      title: 'Learn More',
      url: 'https://www.burgerandlobster.com/',
      target: '_blank',
    },
    ubication: {
      address: '132 W 43rd St, New York, NY 10036, United States',
      lat: 40.7559517,
      lng: -73.9851995,
      zoom: 14,
      place_id: 'ChIJf4PUOlVYwokRyauhSgUGpr8',
      name: '132 W 43rd St',
      street_number: '132',
      street_name: 'West 43rd Street',
      street_name_short: 'W 43rd St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 617,
    title: 'Ootoya',
    size: 'little',
    colorfont: 'white',
    color: '#2a5780',
    num: 30,
    link: { title: 'Learn More ', url: 'https://ootoya.us/', target: '_blank' },
    ubication: {
      address: '141 W 41st St, New York, NY 10036, United States',
      lat: 40.7549249,
      lng: -73.9859683,
      zoom: 14,
      place_id: 'ChIJxVIt16pZwokRVFgIiXAoPQI',
      name: '141 W 41st St',
      street_number: '141',
      street_name: 'West 41st Street',
      street_name_short: 'W 41st St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 615,
    title: 'Charlie Palmer Steak',
    size: 'big',
    colorfont: 'white',
    color: '#2a5780',
    num: 31,
    link: {
      title: 'Learn More ',
      url: 'https://www.charliepalmersteak.com/',
      target: '_blank',
    },
    ubication: {
      address: '135 W 42nd St, New York, NY 10036, United States',
      lat: 40.7555597,
      lng: -73.9853213,
      zoom: 17,
      place_id: 'ChIJ2VCDLVVYwokRuNe7-a22-7I',
      name: '135 W 42nd St',
      street_number: '135',
      street_name: 'West 42nd Street',
      street_name_short: 'W 42nd St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'restaurants-dining',
    child_cats: [],
  },
  {
    ID: 345,
    title: 'The Knickerbocker',
    size: 'big',
    colorfont: 'dark',
    color: '#ef8a62',
    num: 32,
    link: {
      title: 'Learn More',
      url: 'https://theknickerbocker.com/',
      target: '_blank',
    },
    ubication: {
      address: '142 W 42nd St, New York, NY 10036, USA',
      lat: 40.75532678322251,
      lng: -73.98594493173827,
      zoom: 17,
      place_id: 'ChIJbd6eKqtZwokR38_kPNvogT0',
      street_number: '142',
      street_name: 'West 42nd Street',
      street_name_short: 'W 42nd St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'hotel',
    child_cats: [],
  },
  {
    ID: 346,
    title: 'Millennium Broadway Hotel',
    size: 'little',
    colorfont: 'dark',
    color: '#ef8a62',
    num: 33,
    link: { title: 'Learn More', url: 'http://hilton.com', target: '_blank' },
    ubication: {
      address: '120 W 45th St, New York, NY 10036, USA',
      lat: 40.757090349077686,
      lng: -73.98437852167358,
      zoom: 16,
      place_id: 'ChIJxWrLb1VYwokRkDKzLVYDmmI',
      street_number: '120',
      street_name: 'West 45th Street',
      street_name_short: 'W 45th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'hotel',
    child_cats: [],
  },
  {
    ID: 357,
    title: 'New York Marriott Marquis',
    size: 'big',
    colorfont: 'dark',
    color: '#ef8a62',
    num: 34,
    link: { title: 'Learn More', url: 'http://marriott.com', target: '_blank' },
    ubication: {
      address: '1535 Broadway, New York, NY 10036, United States',
      lat: 40.7585862,
      lng: -73.98582019999999,
      zoom: 17,
      place_id: 'ChIJ6UYFrlVYwokRMb8DsvI4m4U',
      name: '1535 Broadway',
      street_number: '1535',
      street_name: 'Broadway',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'hotel',
    child_cats: [],
  },
  {
    ID: 359,
    title: 'Row NYC',
    size: 'little',
    colorfont: 'dark',
    color: '#ef8a62',
    num: 36,
    link: {
      title: 'Learn More',
      url: 'https://rownewyork.org/',
      target: '_blank',
    },
    ubication: {
      address: 'Row New York, 252 W 37th St, NY, 10018, United States',
      lat: 40.7542535,
      lng: -73.9917332,
      zoom: 17,
      place_id: 'ChIJA9dSkiZZwokRtZsaDbmGPJc',
      name: 'Row New York',
      street_number: '252',
      street_name: 'West 37th Street',
      street_name_short: 'W 37th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10018',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'hotel',
    child_cats: [],
  },
  {
    ID: 360,
    title: 'W New York',
    size: 'big',
    colorfont: 'dark',
    color: '#ef8a62',
    num: 37,
    link: { title: 'Learn More', url: 'http://marriott.com', target: '_blank' },
    ubication: {
      address: '1557 Broadway, New York, NY 10036, USA',
      lat: 40.759171573417404,
      lng: -73.98555511349181,
      zoom: 17,
      place_id: 'ChIJrfgCupBZwokRQKXjUK2TzVE',
      street_number: '1557',
      street_name: 'Broadway',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'hotel',
    child_cats: [],
  },
  {
    ID: 361,
    title: 'Renaissance New York',
    size: 'little',
    colorfont: 'dark',
    color: '#ef8a62',
    num: 38,
    link: { title: 'Learn More', url: 'http://marriott.com', target: '_blank' },
    ubication: {
      address:
        'Renaissance New York Times Square Hotel, W 48th St, NY, 10036, United States',
      lat: 40.7598399,
      lng: -73.98438759999999,
      zoom: 17,
      place_id: 'ChIJ76A33VVYwokRL8jY1bRt1y8',
      name: 'Renaissance New York Times Square Hotel',
      street_name: 'West 48th Street',
      street_name_short: 'W 48th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'hotel',
    child_cats: [],
  },
  {
    ID: 362,
    title: 'InterContinental',
    size: 'little',
    colorfont: 'dark',
    color: '#ef8a62',
    num: 39,
    link: { title: 'Learn More', url: 'http://ihg.com', target: '_blank' },
    ubication: {
      address:
        'InterContinental New York Times Square, 300 W 44th St, NY, 10036, United States',
      lat: 40.7586603,
      lng: -73.98954429999999,
      zoom: 17,
      place_id: 'ChIJmR9pnVNYwokRqHaZ7QNK4fE',
      name: 'InterContinental New York Times Square',
      street_number: '300',
      street_name: 'West 44th Street',
      street_name_short: 'W 44th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'hotel',
    child_cats: [],
  },
  {
    ID: 363,
    title: 'The Chatwal',
    size: 'little',
    colorfont: 'dark',
    color: '#ef8a62',
    num: 40,
    link: { title: 'Learn More', url: 'http://marriott.com', target: '_blank' },
    ubication: {
      address: '128 W 44th St, New York, NY 10036, USA',
      lat: 40.7567458554349,
      lng: -73.98464461534425,
      zoom: 16,
      place_id: 'ChIJXwtPFVVYwokRRGCpoBM4WgI',
      street_number: '128',
      street_name: 'West 44th Street',
      street_name_short: 'W 44th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'hotel',
    child_cats: [],
  },
  {
    ID: 364,
    title: 'Hyatt Centric',
    size: 'little',
    colorfont: 'dark',
    color: '#ef8a62',
    num: 41,
    link: { title: 'Learn More', url: 'http://hyatt.com', target: '_blank' },
    ubication: {
      address:
        'Hyatt Centric Times Square New York, 135 W 45th St, NY, 10036, United States',
      lat: 40.7575283,
      lng: -73.9840627,
      zoom: 17,
      place_id: 'ChIJldZjdlVYwokRT_yKDywRlaw',
      name: 'Hyatt Centric Times Square New York',
      street_number: '135',
      street_name: 'West 45th Street',
      street_name_short: 'W 45th St',
      city: 'New York',
      state: 'New York',
      state_short: 'NY',
      post_code: '10036',
      country: 'United States',
      country_short: 'US',
    },
    main_cat: 'hotel',
    child_cats: [],
  },
]
